name 'campfield-chattr'
version '0.1.0'
source 'git://github.com/campfield/puppet-module-chattr.git'
author 'campfield'
license 'Apache License, Version 2.0'
summary 'deal with immutable attribute bug'
description 'manage chattr attributes'
project_page 'https://github.com/campfield/puppet-module-chattr'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
